version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '5000:5000'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: ${PRISMA_PORT}
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            port: 5432
            user: oasis
            password: backend
            database: oasis
  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: oasis
      POSTGRES_PASSWORD: backend
      POSTGRES_DB: oasis
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
